name: CI

# Run the CI on PRs and pushes to main.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    name: Run
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        dc:
          - dmd-latest
          - ldc-latest

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    env:
      CODECOV_DIR: 'build/code-coverage'

    steps:
    - name: Prepare D compiler and Dub package manager
      uses: dlang-community/setup-dlang@v1
      with:
          compiler: ${{ matrix.dc }}

    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: 'Build and test'
      run: ./scripts/ci.sh

    - name: 'Upload coverage to Codecov'
      if: matrix.dc == 'dmd-latest'
      uses: codecov/codecov-action@v3
      with:
        directory: ${{ env.CODECOV_DIR }}
