name: CI

# Run the CI on PRs and pushes to main.
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  main:
    name: Run
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest ]
        dc:
          - dmd
          - ldc2

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    env:
      CODECOV_DIR: 'build/code-coverage'
      DC: ${{ matrix.dc }}

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Install Nix package manager
      uses: cachix/install-nix-action@v17

    - name: Build Nix dev shell
      run: nix build '.#devShell.x86_64-linux'

    - name: 'Build and test'
      run: nix develop -c ./scripts/ci.sh

    - name: 'Upload coverage to Codecov'
      if: matrix.dc == 'dmd-latest'
      uses: codecov/codecov-action@v3
      with:
        directory: ${{ env.CODECOV_DIR }}
